import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#5c403f',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'outline': '#906f6e',
        'outline-variant': '#e5bdbb',
        'surface-tint': '#bf0229',
        'primary': '#9e001f',
        'on-primary': '#ffffff',
        'primary-container': '#c8102e',
        'on-primary-container': '#ffdad8',
        'inverse-primary': '#ffb3b1',
        'secondary': '#5d5e61',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2e2e5',
        'on-secondary-container': '#636467',
        'tertiary': '#454d59',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5d6571',
        'on-tertiary-container': '#dbe3f1',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b1',
        'on-primary-fixed': '#410007',
        'on-primary-fixed-variant': '#92001c',
        'secondary-fixed': '#e2e2e5',
        'secondary-fixed-dim': '#c6c6c9',
        'on-secondary-fixed': '#1a1c1e',
        'on-secondary-fixed-variant': '#454749',
        'tertiary-fixed': '#dbe3f1',
        'tertiary-fixed-dim': '#bfc7d5',
        'on-tertiary-fixed': '#141c26',
        'on-tertiary-fixed-variant': '#3f4753',
        'background': '#f8f9fa',
        'on-background': '#191c1d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'margin': '1rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
        'gutter': '1.5rem',
        'gutter-desktop': '2rem',
      },
      fontFamily: {
        'display-xl': ['"Space Grotesk"', 'sans-serif'],
        'display-xl-mobile': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg-mobile': ['"Space Grotesk"', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'headline-sm': ['"Space Grotesk"', 'sans-serif'],
        'body-lg': ['"Inter"', 'sans-serif'],
        'body-md': ['"Inter"', 'sans-serif'],
        'body-sm': ['"Inter"', 'sans-serif'],
        'button-text': ['"Inter"', 'sans-serif'],
        'label-technical': ['"JetBrains Mono"', 'monospace'],
        'label-mono-sm': ['"JetBrains Mono"', 'monospace'],
        sans: ['"Inter"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        space: ['"Space Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-xl-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '0', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '30px', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '25px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '400' }],
        'button-text': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-technical': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '500' }],
        'label-mono-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
